version: "3.8"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community  # 8-community
    volumes:
      - .\data:/opt/sonarqube/data
    ports:
      - "9000:9000"
networks:
  default:
    name: network_jenkins
    external: true
