version: "3.8"
services:
  jboss_wildfly:
    container_name: jboss_wildfly
    image: jboss/wildfly:23.0.1.Final
    ports:
      - "8080:8080"
      - "9990:9990"
    command: ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
networks:
  default:
    external:
      name: backend_database
