version: "3.8"
services:
  mysql_database:
    container_name: mysql_database
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'abc123abc'
    volumes:
      - .\data:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    name: springboot_demo_database
    driver: bridge